services:
  # Service 1: La base de données PostgreSQL
  postgres-db:
    image: postgres:15
    container_name: user_db_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d userdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Service 2: L'interface graphique pour gérer la base de données
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db

  # Service 3: Notre application Spring qui tourne sur Tomcat
  tomcat:
    # Indique à Docker Compose de construire l'image en utilisant le Dockerfile
    # qui se trouve dans le répertoire courant ('.')
    build: .
    container_name: tomcat_container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
        postgres-db:
          condition: service_healthy

volumes:
  postgres-data: {}